using Freexcel.Core.Model;

namespace Freexcel.Core.IO;

public sealed partial class NativeJsonAdapter
{
    private static ChartModel? TryLoadChart(ChartDto? chartDto, SheetId sheetId)
    {
        if (chartDto?.DataRange is null)
            return null;

        try
        {
            var chart = new ChartModel
            {
                Name = chartDto.Name,
                Type = chartDto.Type,
                DataRange = GridRange.Parse(chartDto.DataRange, sheetId),
                IsVisible = chartDto.IsVisible,
                IsPivotChart = chartDto.IsPivotChart,
                PivotSourceSheetName = chartDto.PivotSourceSheetName,
                PivotTableName = chartDto.PivotTableName,
                PivotSourceFormatId = chartDto.PivotSourceFormatId,
                PivotCacheId = chartDto.PivotCacheId,
                ChartStyleId = chartDto.ChartStyleId,
                PivotFormatsXml = chartDto.PivotFormatsXml,
                Uses1904DateSystem = chartDto.Uses1904DateSystem,
                Language = chartDto.Language,
                ColorMapOverride = chartDto.ColorMapOverride,
                ExternalData = chartDto.ExternalData,
                PlotAreaLayout = chartDto.PlotAreaLayout,
                LegendLayout = chartDto.LegendLayout,
                RoundedCorners = chartDto.RoundedCorners,
                BlankDisplayMode = chartDto.BlankDisplayMode,
                ShowDataLabelsOverMaximum = chartDto.ShowDataLabelsOverMaximum,
                AutoTitleDeleted = chartDto.AutoTitleDeleted,
                ShowDataInHiddenRowsAndColumns = chartDto.ShowDataInHiddenRowsAndColumns,
                Protection = chartDto.Protection,
                PrintSettings = chartDto.PrintSettings,
                ThreeDView = chartDto.ThreeDView,
                FloorFormat = ToChartSurfaceFormat(chartDto.FloorFormat),
                SideWallFormat = ToChartSurfaceFormat(chartDto.SideWallFormat),
                BackWallFormat = ToChartSurfaceFormat(chartDto.BackWallFormat),
                ShowPivotChartFieldButtons = chartDto.ShowPivotChartFieldButtons,
                ShowPivotChartReportFilterButtons = chartDto.ShowPivotChartReportFilterButtons,
                ShowPivotChartAxisFieldButtons = chartDto.ShowPivotChartAxisFieldButtons,
                ShowPivotChartValueFieldButtons = chartDto.ShowPivotChartValueFieldButtons,
                FirstRowIsHeader = chartDto.FirstRowIsHeader,
                FirstColIsCategories = chartDto.FirstColIsCategories,
                Title = chartDto.Title,
                TitleLayout = chartDto.TitleLayout,
                TitleOverlay = chartDto.TitleOverlay,
                XAxisTitle = chartDto.XAxisTitle,
                XAxisTitleLayout = chartDto.XAxisTitleLayout,
                YAxisTitle = chartDto.YAxisTitle,
                YAxisTitleLayout = chartDto.YAxisTitleLayout,
                HideXAxis = chartDto.HideXAxis,
                HideYAxis = chartDto.HideYAxis,
                XAxisPosition = chartDto.XAxisPosition,
                YAxisPosition = chartDto.YAxisPosition,
                ChartTitleTextColor = chartDto.ChartTitleTextColor,
                ChartTitleTextThemeColor = ToThemeColorReference(chartDto.ChartTitleTextThemeColor),
                ChartTitleFontSize = chartDto.ChartTitleFontSize,
                AxisTitleTextColor = chartDto.AxisTitleTextColor,
                AxisTitleTextThemeColor = ToThemeColorReference(chartDto.AxisTitleTextThemeColor),
                AxisTitleFontSize = chartDto.AxisTitleFontSize,
                ChartAreaFillColor = chartDto.ChartAreaFillColor,
                ChartAreaFillThemeColor = ToThemeColorReference(chartDto.ChartAreaFillThemeColor),
                ChartAreaBorderColor = chartDto.ChartAreaBorderColor,
                ChartAreaBorderThemeColor = ToThemeColorReference(chartDto.ChartAreaBorderThemeColor),
                ChartAreaBorderThickness = chartDto.ChartAreaBorderThickness,
                PlotAreaFillColor = chartDto.PlotAreaFillColor,
                PlotAreaFillThemeColor = ToThemeColorReference(chartDto.PlotAreaFillThemeColor),
                PlotAreaBorderColor = chartDto.PlotAreaBorderColor,
                PlotAreaBorderThemeColor = ToThemeColorReference(chartDto.PlotAreaBorderThemeColor),
                PlotAreaBorderThickness = chartDto.PlotAreaBorderThickness,
                LegendTextColor = chartDto.LegendTextColor,
                LegendTextThemeColor = ToThemeColorReference(chartDto.LegendTextThemeColor),
                LegendFillColor = chartDto.LegendFillColor,
                LegendFillThemeColor = ToThemeColorReference(chartDto.LegendFillThemeColor),
                LegendBorderColor = chartDto.LegendBorderColor,
                LegendBorderThemeColor = ToThemeColorReference(chartDto.LegendBorderThemeColor),
                LegendBorderThickness = chartDto.LegendBorderThickness,
                LegendFontSize = chartDto.LegendFontSize,
                DoughnutHoleSize = chartDto.DoughnutHoleSize,
                FirstSliceAngle = chartDto.FirstSliceAngle,
                ExplodedSliceIndex = chartDto.ExplodedSliceIndex,
                ExplodedSliceDistance = chartDto.ExplodedSliceDistance,
                XAxisMinimum = chartDto.XAxisMinimum,
                XAxisMaximum = chartDto.XAxisMaximum,
                XAxisMajorUnit = chartDto.XAxisMajorUnit,
                XAxisMinorUnit = chartDto.XAxisMinorUnit,
                XAxisLogScale = chartDto.XAxisLogScale,
                XAxisLogBase = chartDto.XAxisLogBase,
                XAxisReverseOrder = chartDto.XAxisReverseOrder,
                XAxisNumberFormat = chartDto.XAxisNumberFormat,
                XAxisNumberFormatCode = chartDto.XAxisNumberFormatCode,
                XAxisNumberFormatSourceLinked = chartDto.XAxisNumberFormatSourceLinked,
                ShowXAxisMajorGridlines = chartDto.ShowXAxisMajorGridlines,
                ShowXAxisMinorGridlines = chartDto.ShowXAxisMinorGridlines,
                XAxisIsDateAxis = chartDto.XAxisIsDateAxis,
                XAxisMajorGridlineColor = chartDto.XAxisMajorGridlineColor,
                XAxisMinorGridlineColor = chartDto.XAxisMinorGridlineColor,
                XAxisGridlineThickness = chartDto.XAxisGridlineThickness,
                XAxisMajorTickStyle = chartDto.XAxisMajorTickStyle,
                XAxisMinorTickStyle = chartDto.XAxisMinorTickStyle,
                ShowXAxisLabels = chartDto.ShowXAxisLabels,
                XAxisTickLabelPosition = chartDto.XAxisTickLabelPosition,
                XAxisLabelTextColor = chartDto.XAxisLabelTextColor,
                XAxisLabelTextThemeColor = ToThemeColorReference(chartDto.XAxisLabelTextThemeColor),
                XAxisLabelFontSize = chartDto.XAxisLabelFontSize,
                XAxisLabelAngle = chartDto.XAxisLabelAngle,
                XAxisLabelSkip = Math.Max(0, chartDto.XAxisLabelSkip),
                XAxisTickMarkSkip = Math.Max(0, chartDto.XAxisTickMarkSkip),
                XAxisLabelOffset = Math.Max(0, chartDto.XAxisLabelOffset),
                XAxisNoMultiLevelLabels = chartDto.XAxisNoMultiLevelLabels,
                XAxisLabelAlignment = chartDto.XAxisLabelAlignment,
                XAxisBaseTimeUnit = chartDto.XAxisBaseTimeUnit,
                XAxisMajorTimeUnit = chartDto.XAxisMajorTimeUnit,
                XAxisMinorTimeUnit = chartDto.XAxisMinorTimeUnit,
                XAxisLineColor = chartDto.XAxisLineColor,
                XAxisLineThickness = chartDto.XAxisLineThickness,
                XAxisCrosses = chartDto.XAxisCrosses,
                XAxisCrossesAt = chartDto.XAxisCrossesAt,
                XAxisCrossBetween = chartDto.XAxisCrossBetween,
                XAxisDisplayUnit = chartDto.XAxisDisplayUnit,
                XAxisCustomDisplayUnit = chartDto.XAxisCustomDisplayUnit,
                YAxisMinimum = chartDto.YAxisMinimum,
                YAxisMaximum = chartDto.YAxisMaximum,
                YAxisMajorUnit = chartDto.YAxisMajorUnit,
                YAxisMinorUnit = chartDto.YAxisMinorUnit,
                YAxisLogScale = chartDto.YAxisLogScale,
                YAxisLogBase = chartDto.YAxisLogBase,
                YAxisReverseOrder = chartDto.YAxisReverseOrder,
                YAxisNumberFormat = chartDto.YAxisNumberFormat,
                YAxisNumberFormatCode = chartDto.YAxisNumberFormatCode,
                YAxisNumberFormatSourceLinked = chartDto.YAxisNumberFormatSourceLinked,
                ShowYAxisMajorGridlines = chartDto.ShowYAxisMajorGridlines,
                ShowYAxisMinorGridlines = chartDto.ShowYAxisMinorGridlines,
                YAxisMajorGridlineColor = chartDto.YAxisMajorGridlineColor,
                YAxisMinorGridlineColor = chartDto.YAxisMinorGridlineColor,
                YAxisGridlineThickness = chartDto.YAxisGridlineThickness,
                YAxisMajorTickStyle = chartDto.YAxisMajorTickStyle,
                YAxisMinorTickStyle = chartDto.YAxisMinorTickStyle,
                ShowYAxisLabels = chartDto.ShowYAxisLabels,
                YAxisTickLabelPosition = chartDto.YAxisTickLabelPosition,
                YAxisLabelTextColor = chartDto.YAxisLabelTextColor,
                YAxisLabelTextThemeColor = ToThemeColorReference(chartDto.YAxisLabelTextThemeColor),
                YAxisLabelFontSize = chartDto.YAxisLabelFontSize,
                YAxisLabelAngle = chartDto.YAxisLabelAngle,
                YAxisLineColor = chartDto.YAxisLineColor,
                YAxisLineThickness = chartDto.YAxisLineThickness,
                YAxisCrosses = chartDto.YAxisCrosses,
                YAxisCrossesAt = chartDto.YAxisCrossesAt,
                YAxisCrossBetween = chartDto.YAxisCrossBetween,
                YAxisDisplayUnit = chartDto.YAxisDisplayUnit,
                YAxisCustomDisplayUnit = chartDto.YAxisCustomDisplayUnit,
                DataTable = chartDto.DataTable,
                BarGapWidth = chartDto.BarGapWidth,
                BarOverlap = chartDto.BarOverlap,
                VaryColorsByPoint = chartDto.VaryColorsByPoint,
                BubbleScale = chartDto.BubbleScale,
                ShowNegativeBubbles = chartDto.ShowNegativeBubbles,
                BubbleSizeRepresents = chartDto.BubbleSizeRepresents,
                StockSubtype = chartDto.StockSubtype,
                LegendPosition = chartDto.LegendPosition,
                LegendOverlay = chartDto.LegendOverlay,
                ShowLegend = chartDto.ShowLegend,
                ShowDataLabels = chartDto.ShowDataLabels,
                DataLabelPosition = chartDto.DataLabelPosition,
                ShowDataLabelValue = chartDto.ShowDataLabelValue,
                ShowDataLabelLegendKey = chartDto.ShowDataLabelLegendKey,
                ShowDataLabelBubbleSize = chartDto.ShowDataLabelBubbleSize,
                ShowDataLabelCategoryName = chartDto.ShowDataLabelCategoryName,
                ShowDataLabelSeriesName = chartDto.ShowDataLabelSeriesName,
                ShowDataLabelPercentage = chartDto.ShowDataLabelPercentage,
                DataLabelSeparator = chartDto.DataLabelSeparator,
                DataLabelNumberFormat = chartDto.DataLabelNumberFormat,
                DataLabelNumberFormatCode = chartDto.DataLabelNumberFormatCode,
                DataLabelNumberFormatSourceLinked = chartDto.DataLabelNumberFormatSourceLinked,
                ShowDataLabelCallouts = chartDto.ShowDataLabelCallouts,
                DataLabelFillColor = chartDto.DataLabelFillColor,
                DataLabelFillThemeColor = ToThemeColorReference(chartDto.DataLabelFillThemeColor),
                DataLabelBorderColor = chartDto.DataLabelBorderColor,
                DataLabelBorderThemeColor = ToThemeColorReference(chartDto.DataLabelBorderThemeColor),
                DataLabelTextColor = chartDto.DataLabelTextColor,
                DataLabelTextThemeColor = ToThemeColorReference(chartDto.DataLabelTextThemeColor),
                DataLabelBorderThickness = chartDto.DataLabelBorderThickness,
                DataLabelFontSize = chartDto.DataLabelFontSize,
                DataLabelAngle = chartDto.DataLabelAngle,
                ShowLinearTrendline = chartDto.ShowLinearTrendline,
                TrendlineName = chartDto.TrendlineName,
                TrendlineType = chartDto.TrendlineType,
                TrendlinePeriod = chartDto.TrendlinePeriod,
                TrendlineOrder = chartDto.TrendlineOrder,
                TrendlineForward = chartDto.TrendlineForward,
                TrendlineBackward = chartDto.TrendlineBackward,
                TrendlineIntercept = chartDto.TrendlineIntercept,
                ShowTrendlineEquation = chartDto.ShowTrendlineEquation,
                ShowTrendlineRSquared = chartDto.ShowTrendlineRSquared,
                TrendlineLabelNumberFormatCode = chartDto.TrendlineLabelNumberFormatCode,
                TrendlineLabelNumberFormatSourceLinked = chartDto.TrendlineLabelNumberFormatSourceLinked,
                TrendlineLabelLayout = chartDto.TrendlineLabelLayout,
                TrendlineLabelFillColor = chartDto.TrendlineLabelFillColor,
                TrendlineLabelFillThemeColor = ToThemeColorReference(chartDto.TrendlineLabelFillThemeColor),
                TrendlineLabelBorderColor = chartDto.TrendlineLabelBorderColor,
                TrendlineLabelBorderThemeColor = ToThemeColorReference(chartDto.TrendlineLabelBorderThemeColor),
                TrendlineLabelBorderThickness = chartDto.TrendlineLabelBorderThickness,
                TrendlineLabelTextColor = chartDto.TrendlineLabelTextColor,
                TrendlineLabelTextThemeColor = ToThemeColorReference(chartDto.TrendlineLabelTextThemeColor),
                TrendlineLabelFontSize = chartDto.TrendlineLabelFontSize,
                TrendlineLabelAngle = chartDto.TrendlineLabelAngle,
                TrendlineColor = chartDto.TrendlineColor,
                TrendlineThemeColor = ToThemeColorReference(chartDto.TrendlineThemeColor),
                TrendlineThickness = chartDto.TrendlineThickness,
                TrendlineDashStyle = chartDto.TrendlineDashStyle,
                ShowErrorBars = chartDto.ShowErrorBars,
                ErrorBarKind = chartDto.ErrorBarKind,
                ErrorBarAxisDirection = chartDto.ErrorBarAxisDirection,
                ErrorBarDirection = chartDto.ErrorBarDirection,
                ErrorBarValue = chartDto.ErrorBarValue,
                ErrorBarPlusRangeFormula = chartDto.ErrorBarPlusRangeFormula,
                ErrorBarMinusRangeFormula = chartDto.ErrorBarMinusRangeFormula,
                ErrorBarEndCaps = chartDto.ErrorBarEndCaps,
                ErrorBarColor = chartDto.ErrorBarColor,
                ErrorBarThemeColor = ToThemeColorReference(chartDto.ErrorBarThemeColor),
                ErrorBarThickness = chartDto.ErrorBarThickness,
                ErrorBarDashStyle = chartDto.ErrorBarDashStyle,
                ShowDropLines = chartDto.ShowDropLines,
                DropLineColor = chartDto.DropLineColor,
                DropLineThemeColor = ToThemeColorReference(chartDto.DropLineThemeColor),
                DropLineThickness = chartDto.DropLineThickness,
                DropLineDashStyle = chartDto.DropLineDashStyle,
                ShowHighLowLines = chartDto.ShowHighLowLines,
                HighLowLineColor = chartDto.HighLowLineColor,
                HighLowLineThemeColor = ToThemeColorReference(chartDto.HighLowLineThemeColor),
                HighLowLineThickness = chartDto.HighLowLineThickness,
                HighLowLineDashStyle = chartDto.HighLowLineDashStyle,
                ShowSeriesLines = chartDto.ShowSeriesLines,
                SeriesLineColor = chartDto.SeriesLineColor,
                SeriesLineThemeColor = ToThemeColorReference(chartDto.SeriesLineThemeColor),
                SeriesLineThickness = chartDto.SeriesLineThickness,
                SeriesLineDashStyle = chartDto.SeriesLineDashStyle,
                ShowUpDownBars = chartDto.ShowUpDownBars,
                UpDownBarGapWidth = chartDto.UpDownBarGapWidth,
                UpBarFillColor = chartDto.UpBarFillColor,
                UpBarFillThemeColor = ToThemeColorReference(chartDto.UpBarFillThemeColor),
                UpBarBorderColor = chartDto.UpBarBorderColor,
                UpBarBorderThemeColor = ToThemeColorReference(chartDto.UpBarBorderThemeColor),
                UpBarBorderThickness = chartDto.UpBarBorderThickness,
                DownBarFillColor = chartDto.DownBarFillColor,
                DownBarFillThemeColor = ToThemeColorReference(chartDto.DownBarFillThemeColor),
                DownBarBorderColor = chartDto.DownBarBorderColor,
                DownBarBorderThemeColor = ToThemeColorReference(chartDto.DownBarBorderThemeColor),
                DownBarBorderThickness = chartDto.DownBarBorderThickness,
                ShowSecondaryAxis = chartDto.ShowSecondaryAxis,
                SecondaryAxisSeriesIndexes = chartDto.SecondaryAxisSeriesIndexes ?? [],
                ComboLineSeriesIndexes = chartDto.ComboLineSeriesIndexes ?? [],
                SeriesFormats = chartDto.SeriesFormats ?? [],
                PointDataLabelFormats = chartDto.PointDataLabelFormats ?? [],
                UseComboLineForSecondarySeries = chartDto.UseComboLineForSecondarySeries,
                Left = chartDto.Left,
                Top = chartDto.Top,
                Width = NativeJsonValueSanitizer.PositiveFiniteOrDefault(chartDto.Width, 400),
                Height = NativeJsonValueSanitizer.PositiveFiniteOrDefault(chartDto.Height, 300),
                DrawingAnchorKind = chartDto.DrawingAnchorKind
            };
            SanitizeLoadedChart(chart);
            return chart;
        }
        catch (FormatException)
        {
            return null;
        }
    }

    private static ChartSurfaceFormatModel? ToChartSurfaceFormat(ChartSurfaceFormatDto? dto) =>
        dto is null
            ? null
            : new ChartSurfaceFormatModel
            {
                FillColor = dto.FillColor,
                FillThemeColor = ToThemeColorReference(dto.FillThemeColor),
                BorderColor = dto.BorderColor,
                BorderThemeColor = ToThemeColorReference(dto.BorderThemeColor),
                BorderThickness = dto.BorderThickness
            };

}

