using Freexcel.Core.Model;

namespace Freexcel.Core.Commands;

public sealed record ChartLayoutOptions(
    string? Title = null,
    string? XAxisTitle = null,
    string? YAxisTitle = null,
    CellColor? ChartTitleTextColor = null,
    double? ChartTitleFontSize = null,
    CellColor? AxisTitleTextColor = null,
    double? AxisTitleFontSize = null,
    CellColor? ChartAreaFillColor = null,
    CellColor? PlotAreaFillColor = null,
    CellColor? PlotAreaBorderColor = null,
    double? PlotAreaBorderThickness = null,
    CellColor? LegendTextColor = null,
    CellColor? LegendFillColor = null,
    CellColor? LegendBorderColor = null,
    double? LegendBorderThickness = null,
    double? LegendFontSize = null,
    double? DoughnutHoleSize = null,
    double? FirstSliceAngle = null,
    int? ExplodedSliceIndex = null,
    double? ExplodedSliceDistance = null,
    double? XAxisMinimum = null,
    double? XAxisMaximum = null,
    double? XAxisMajorUnit = null,
    double? XAxisMinorUnit = null,
    bool? XAxisLogScale = null,
    ChartDataLabelNumberFormat? XAxisNumberFormat = null,
    bool? ShowXAxisMajorGridlines = null,
    bool? ShowXAxisMinorGridlines = null,
    CellColor? XAxisMajorGridlineColor = null,
    CellColor? XAxisMinorGridlineColor = null,
    double? XAxisGridlineThickness = null,
    ChartAxisTickStyle? XAxisMajorTickStyle = null,
    ChartAxisTickStyle? XAxisMinorTickStyle = null,
    bool? ShowXAxisLabels = null,
    CellColor? XAxisLabelTextColor = null,
    double? XAxisLabelFontSize = null,
    double? XAxisLabelAngle = null,
    CellColor? XAxisLineColor = null,
    double? XAxisLineThickness = null,
    double? YAxisMinimum = null,
    double? YAxisMaximum = null,
    double? YAxisMajorUnit = null,
    double? YAxisMinorUnit = null,
    bool? YAxisLogScale = null,
    ChartDataLabelNumberFormat? YAxisNumberFormat = null,
    bool? ShowYAxisMajorGridlines = null,
    bool? ShowYAxisMinorGridlines = null,
    CellColor? YAxisMajorGridlineColor = null,
    CellColor? YAxisMinorGridlineColor = null,
    double? YAxisGridlineThickness = null,
    ChartAxisTickStyle? YAxisMajorTickStyle = null,
    ChartAxisTickStyle? YAxisMinorTickStyle = null,
    bool? ShowYAxisLabels = null,
    CellColor? YAxisLabelTextColor = null,
    double? YAxisLabelFontSize = null,
    double? YAxisLabelAngle = null,
    CellColor? YAxisLineColor = null,
    double? YAxisLineThickness = null,
    bool ClearXAxisBounds = false,
    bool ClearYAxisBounds = false,
    ChartLegendPosition? LegendPosition = null,
    bool? LegendOverlay = null,
    bool? ShowLegend = null,
    bool? ShowDataLabels = null,
    ChartDataLabelPosition? DataLabelPosition = null,
    bool? ShowDataLabelCategoryName = null,
    bool? ShowDataLabelSeriesName = null,
    bool? ShowDataLabelPercentage = null,
    ChartDataLabelSeparator? DataLabelSeparator = null,
    ChartDataLabelNumberFormat? DataLabelNumberFormat = null,
    bool? ShowDataLabelCallouts = null,
    CellColor? DataLabelFillColor = null,
    CellColor? DataLabelBorderColor = null,
    CellColor? DataLabelTextColor = null,
    double? DataLabelBorderThickness = null,
    double? DataLabelFontSize = null,
    double? DataLabelAngle = null,
    bool? ShowLinearTrendline = null,
    ChartTrendlineType? TrendlineType = null,
    int? TrendlinePeriod = null,
    int? TrendlineOrder = null,
    bool? ShowTrendlineEquation = null,
    bool? ShowTrendlineRSquared = null,
    CellColor? TrendlineColor = null,
    double? TrendlineThickness = null,
    ChartLineDashStyle? TrendlineDashStyle = null,
    bool? ShowErrorBars = null,
    ChartErrorBarKind? ErrorBarKind = null,
    ChartErrorBarDirection? ErrorBarDirection = null,
    double? ErrorBarValue = null,
    bool? ErrorBarEndCaps = null,
    bool? ShowSecondaryAxis = null,
    IReadOnlyList<int>? SecondaryAxisSeriesIndexes = null,
    IReadOnlyList<int>? ComboLineSeriesIndexes = null,
    IReadOnlyList<ChartSeriesFormat>? SeriesFormats = null,
    IReadOnlyList<ChartPointDataLabelFormat>? PointDataLabelFormats = null,
    bool? UseComboLineForSecondarySeries = null,
    WorkbookThemeColorReference? ChartAreaFillThemeColor = null,
    WorkbookThemeColorReference? PlotAreaFillThemeColor = null,
    WorkbookThemeColorReference? PlotAreaBorderThemeColor = null,
    WorkbookThemeColorReference? LegendTextThemeColor = null,
    WorkbookThemeColorReference? LegendFillThemeColor = null,
    WorkbookThemeColorReference? LegendBorderThemeColor = null,
    WorkbookThemeColorReference? DataLabelFillThemeColor = null,
    WorkbookThemeColorReference? DataLabelBorderThemeColor = null,
    WorkbookThemeColorReference? DataLabelTextThemeColor = null,
    WorkbookThemeColorReference? TrendlineThemeColor = null,
    WorkbookThemeColorReference? ChartTitleTextThemeColor = null,
    WorkbookThemeColorReference? AxisTitleTextThemeColor = null,
    WorkbookThemeColorReference? XAxisLabelTextThemeColor = null,
    WorkbookThemeColorReference? YAxisLabelTextThemeColor = null);

public sealed partial class SetChartLayoutCommand : IWorkbookCommand
{
    private readonly SheetId _sheetId;
    private readonly Guid _chartId;
    private readonly ChartLayoutOptions _options;
    private ChartLayoutOptions? _previous;

    public string Label => "Format Chart Layout";

    public SetChartLayoutCommand(SheetId sheetId, Guid chartId, ChartLayoutOptions options)
    {
        _sheetId = sheetId;
        _chartId = chartId;
        _options = options;
    }

    public CommandOutcome Apply(ICommandContext ctx)
    {
        var chart = ctx.GetSheet(_sheetId).Charts.FirstOrDefault(item => item.Id == _chartId);
        if (chart is null)
            return new CommandOutcome(false, "Chart was not found.");

        _previous = Capture(chart);
        ApplyOptions(chart, _options);
        return new CommandOutcome(true, AffectedCells: [chart.DataRange.Start]);
    }

    public void Revert(ICommandContext ctx)
    {
        if (_previous is null)
            return;

        var chart = ctx.GetSheet(_sheetId).Charts.FirstOrDefault(item => item.Id == _chartId);
        if (chart is not null)
            RestoreLayout(chart, _previous);
    }

    private static ChartLayoutOptions Capture(ChartModel chart) =>
        new(
            chart.Title,
            chart.XAxisTitle,
            chart.YAxisTitle,
            chart.ChartTitleTextColor,
            chart.ChartTitleFontSize,
            chart.AxisTitleTextColor,
            chart.AxisTitleFontSize,
            chart.ChartAreaFillColor,
            chart.PlotAreaFillColor,
            chart.PlotAreaBorderColor,
            chart.PlotAreaBorderThickness,
            chart.LegendTextColor,
            chart.LegendFillColor,
            chart.LegendBorderColor,
            chart.LegendBorderThickness,
            chart.LegendFontSize,
            chart.DoughnutHoleSize,
            chart.FirstSliceAngle,
            chart.ExplodedSliceIndex,
            chart.ExplodedSliceDistance,
            chart.XAxisMinimum,
            chart.XAxisMaximum,
            chart.XAxisMajorUnit,
            chart.XAxisMinorUnit,
            chart.XAxisLogScale,
            chart.XAxisNumberFormat,
            chart.ShowXAxisMajorGridlines,
            chart.ShowXAxisMinorGridlines,
            chart.XAxisMajorGridlineColor,
            chart.XAxisMinorGridlineColor,
            chart.XAxisGridlineThickness,
            chart.XAxisMajorTickStyle,
            chart.XAxisMinorTickStyle,
            chart.ShowXAxisLabels,
            chart.XAxisLabelTextColor,
            chart.XAxisLabelFontSize,
            chart.XAxisLabelAngle,
            chart.XAxisLineColor,
            chart.XAxisLineThickness,
            chart.YAxisMinimum,
            chart.YAxisMaximum,
            chart.YAxisMajorUnit,
            chart.YAxisMinorUnit,
            chart.YAxisLogScale,
            chart.YAxisNumberFormat,
            chart.ShowYAxisMajorGridlines,
            chart.ShowYAxisMinorGridlines,
            chart.YAxisMajorGridlineColor,
            chart.YAxisMinorGridlineColor,
            chart.YAxisGridlineThickness,
            chart.YAxisMajorTickStyle,
            chart.YAxisMinorTickStyle,
            chart.ShowYAxisLabels,
            chart.YAxisLabelTextColor,
            chart.YAxisLabelFontSize,
            chart.YAxisLabelAngle,
            chart.YAxisLineColor,
            chart.YAxisLineThickness,
            false,
            false,
            chart.LegendPosition,
            chart.LegendOverlay,
            chart.ShowLegend,
            chart.ShowDataLabels,
            chart.DataLabelPosition,
            chart.ShowDataLabelCategoryName,
            chart.ShowDataLabelSeriesName,
            chart.ShowDataLabelPercentage,
            chart.DataLabelSeparator,
            chart.DataLabelNumberFormat,
            chart.ShowDataLabelCallouts,
            chart.DataLabelFillColor,
            chart.DataLabelBorderColor,
            chart.DataLabelTextColor,
            chart.DataLabelBorderThickness,
            chart.DataLabelFontSize,
            chart.DataLabelAngle,
            chart.ShowLinearTrendline,
            chart.TrendlineType,
            chart.TrendlinePeriod,
            chart.TrendlineOrder,
            chart.ShowTrendlineEquation,
            chart.ShowTrendlineRSquared,
            chart.TrendlineColor,
            chart.TrendlineThickness,
            chart.TrendlineDashStyle,
            chart.ShowErrorBars,
            chart.ErrorBarKind,
            chart.ErrorBarDirection,
            chart.ErrorBarValue,
            chart.ErrorBarEndCaps,
            chart.ShowSecondaryAxis,
            chart.SecondaryAxisSeriesIndexes.ToArray(),
            chart.ComboLineSeriesIndexes.ToArray(),
            chart.SeriesFormats.ToArray(),
            chart.PointDataLabelFormats.ToArray(),
            chart.UseComboLineForSecondarySeries,
            ChartAreaFillThemeColor: chart.ChartAreaFillThemeColor,
            PlotAreaFillThemeColor: chart.PlotAreaFillThemeColor,
            PlotAreaBorderThemeColor: chart.PlotAreaBorderThemeColor,
            LegendTextThemeColor: chart.LegendTextThemeColor,
            LegendFillThemeColor: chart.LegendFillThemeColor,
            LegendBorderThemeColor: chart.LegendBorderThemeColor,
            DataLabelFillThemeColor: chart.DataLabelFillThemeColor,
            DataLabelBorderThemeColor: chart.DataLabelBorderThemeColor,
            DataLabelTextThemeColor: chart.DataLabelTextThemeColor,
            TrendlineThemeColor: chart.TrendlineThemeColor,
            ChartTitleTextThemeColor: chart.ChartTitleTextThemeColor,
            AxisTitleTextThemeColor: chart.AxisTitleTextThemeColor,
            XAxisLabelTextThemeColor: chart.XAxisLabelTextThemeColor,
            YAxisLabelTextThemeColor: chart.YAxisLabelTextThemeColor);

}
